version: '3.1'
services:
  stats-server:
    build: statservice
    container_name: ewm-stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stat-service
      - SPRING_DATASOURCE_USERNAME=ewm-stat-service
      - SPRING_DATASOURCE_PASSWORD=pass
      - DB_NAME=ewm-stat-service
      - DB_HOST=stats-db
      - DB_PORT=6541

  stats-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-stats-bd
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stat-service
      - POSTGRES_USER=ewm-stat-service
      - POSTGRES_PASSWORD=pass

  ewm-service:
    build: mainservice
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm-main-service
      - SPRING_DATASOURCE_USERNAME=ewm-main-service
      - SPRING_DATASOURCE_PASSWORD=pass
      - DB_NAME=ewm-main-service
      - DB_HOST=ewm-db
      - DB_PORT=6542

  ewm-db:
    image: postgres:14-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: ewm-main-service-bd
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main-service
      - POSTGRES_USER=ewm-main-service
      - POSTGRES_PASSWORD=pass
